//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFX.SECParser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMFX.SECParser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;parser&gt;
        ///  &lt;namespaces&gt;
        ///  &lt;/namespaces&gt;
        ///  &lt;sections&gt;
        ///    &lt;section name=&quot;StatementOfOperations&quot;&gt;
        ///    &lt;/section&gt;
        ///    &lt;section name=&quot;ComprehensiveIncome&quot;&gt;
        ///    &lt;/section&gt;
        ///    &lt;section name=&quot;BalanceSheet&quot;&gt;
        ///    &lt;/section&gt;
        ///    &lt;section name=&quot;CashFlowStatement&quot;&gt;
        ///    &lt;/section&gt;
        ///    &lt;section name=&quot;EarningsPerShare&quot;&gt;
        ///    &lt;/section&gt;    
        ///  &lt;/sections&gt;
        ///&lt;/parser&gt;
        ///
        ///.
        /// </summary>
        internal static string AAPL {
            get {
                return ResourceManager.GetString("AAPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;parser&gt;
        ///  &lt;namespaces&gt;
        ///    &lt;namespace ns=&quot;link&quot; uri=&quot;http://www.xbrl.org/2003/linkbase&quot; /&gt;
        ///    &lt;namespace ns=&quot;nonnum&quot; uri=&quot;http://www.xbrl.org/dtr/type/non-numeric&quot; /&gt;
        ///    &lt;namespace ns=&quot;num&quot; uri=&quot;http://www.xbrl.org/dtr/type/numeric&quot; /&gt;
        ///    &lt;namespace ns=&quot;srt-types&quot; uri=&quot;http://fasb.org/srt-types/2019-01-31&quot; /&gt;
        ///    &lt;namespace ns=&quot;us-gaap&quot; uri=&quot;http://fasb.org/us-gaap/2019-01-31&quot; /&gt;
        ///    &lt;namespace ns=&quot;us-types&quot; uri=&quot;http://fasb.org/us-types/2019-01-31&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SECCommonTags {
            get {
                return ResourceManager.GetString("SECCommonTags", resourceCulture);
            }
        }
    }
}
