//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLSXMLGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLSXMLGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUUR0000SA0
        ///CUSR0000SA0
        ///CUUR0000SA0L1E
        ///CUSR0000SA0L1E
        ///CUUR0000SAM1
        ///CUUR0000SEMC01
        ///CUUR0000SEMC
        ///CUUR0000SS5702
        ///CUUR0000SS5703
        ///CUUR0000SEMC02
        ///CUUR0100SEMC
        ///CUUR0100SAM1
        ///CUUR0300SAM1
        ///CUUR0300SEMC
        ///CUUR0400SAM1
        ///CUUR0200SAM1
        ///CUUR0200SEMC
        ///CUUR0400SEMC
        ///CUURA421SA0
        ///CUUR0000SAM
        ///
        ///CWUR0000SA0
        ///CWUR0000AA0
        ///CWURA421SA0
        ///CWSR0000SA0
        ///CWUR0100SA0
        ///CWUR0400SA0
        ///CWURS49ASA0
        ///CWUR0300SA0
        ///CWURA311SA0
        ///CWUR0000SA0L1E
        ///CWURS12ASA0
        ///CWUS0000SA0
        ///CWURS35ASA0
        ///CWUR0200SA0
        ///CWURS49BSA0
        ///CWUSA425SA0
        ///CWURS23ASA0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BLSCodes {
            get {
                return ResourceManager.GetString("BLSCodes", resourceCulture);
            }
        }
    }
}
