//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFX.Service.Mail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMFX.Service.Mail.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;template&gt;
        ///  &lt;type&gt;
        ///    AccountCreatedConfirmation
        ///  &lt;/type&gt;
        ///  &lt;subject&gt;
        ///    [No-Reply] DarkMindFX - Account Created
        ///  &lt;/subject&gt;
        ///  &lt;body&gt;
        ///    &lt;div&gt;
        ///      &lt;div style=&quot;background-color: #888888; font-family: Arial; padding: 20px;&quot;&gt;
        ///        &lt;div style=&quot;color: #FFFFFF;&quot;&gt;
        ///          &lt;b&gt;
        ///            DARKMIND&lt;span style=&quot;color:#FF8C00;&quot;&gt;FX&lt;/span&gt;
        ///          &lt;/b&gt;
        ///        &lt;/div&gt;
        ///      &lt;/div&gt;
        ///      &lt;div style=&quot;font-family: Arial; padding: 20px;&quot;&gt;
        ///        Hello, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountCreatedConfirmation {
            get {
                return ResourceManager.GetString("AccountCreatedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;template&gt;
        ///  &lt;type&gt;
        ///    NewReportNotification
        ///  &lt;/type&gt;
        ///  &lt;subject&gt;
        ///    [No-Reply] DarkMindFX - New Filing: {1}/{2}, Type: {3}
        ///  &lt;/subject&gt;
        ///  &lt;body&gt;
        ///    &lt;div&gt;
        ///      &lt;div style=&quot;background-color: #888888; font-family: Arial; padding: 20px;&quot;&gt;
        ///        &lt;div style=&quot;color: #FFFFFF;&quot;&gt;
        ///          &lt;b&gt;
        ///            DARKMIND&lt;span style=&quot;color:#FF8C00;&quot;&gt;FX&lt;/span&gt;
        ///          &lt;/b&gt;
        ///        &lt;/div&gt;
        ///      &lt;/div&gt;
        ///      &lt;div style=&quot;font-family: Arial; padding: 20px;&quot;&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewReportNotification {
            get {
                return ResourceManager.GetString("NewReportNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;template&gt;
        ///  &lt;type&gt;
        ///    PasswordChangedConfirmation
        ///  &lt;/type&gt;
        ///  &lt;subject&gt;
        ///    [No-Reply] DarkMindFX - Password changed
        ///  &lt;/subject&gt;
        ///  &lt;body&gt;
        ///    &lt;div&gt;
        ///      &lt;div style=&quot;background-color: #888888; font-family: Arial; padding: 20px;&quot;&gt;
        ///        &lt;div style=&quot;color: #FFFFFF;&quot;&gt;
        ///          &lt;b&gt;
        ///            DARKMIND&lt;span style=&quot;color:#FF8C00;&quot;&gt;FX&lt;/span&gt;
        ///          &lt;/b&gt;
        ///        &lt;/div&gt;
        ///      &lt;/div&gt;
        ///      &lt;div style=&quot;font-family: Arial; padding: 20px;&quot;&gt;
        ///        Hell [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordChangedConfirmation {
            get {
                return ResourceManager.GetString("PasswordChangedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;template&gt;
        ///  &lt;type&gt;
        ///    PasswordResetNotification
        ///  &lt;/type&gt;
        ///  &lt;subject&gt;
        ///    [No-Reply] DarkMindFX - Password changed
        ///  &lt;/subject&gt;
        ///  &lt;body&gt;
        ///    &lt;div&gt;
        ///      &lt;div style=&quot;background-color: #888888; font-family: Arial; padding: 20px;&quot;&gt;
        ///        &lt;div style=&quot;color: #FFFFFF;&quot;&gt;
        ///          &lt;b&gt;
        ///            DARKMIND&lt;span style=&quot;color:#FF8C00;&quot;&gt;FX&lt;/span&gt;
        ///          &lt;/b&gt;
        ///        &lt;/div&gt;
        ///      &lt;/div&gt;
        ///      &lt;div style=&quot;font-family: Arial; padding: 20px;&quot;&gt;
        ///        Hello, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordResetNotification {
            get {
                return ResourceManager.GetString("PasswordResetNotification", resourceCulture);
            }
        }
    }
}
